### ISSUE TITLE
Unauthenticated CSW requests returning non-published records 

### ISSUE THREAD

**Issue by asedgmen** [geonetwork-ga/core-geonetwork#25]
Unauthenticated CSW GetRecords requests have access to records that shouldn't be allowed, i.e. records are returned that do not have the "Publish" privilege assigned to the "All" group.  Searches via the GeoNetwork GUI as an anonymous user obey the non-published privilege, whereby the records cannot be retrieved in a search.

**Comment by sppigot** [comment]
Fixed in commit 3ee1fb6862859edf1f230f690853c0064975511b
